export const SESSION_COOKIE_NAME = 'hlbr_del_session';

// The customer's delivery passcode is generated by the storefront (HLBRStore) at order time.
// Keep PASSCODE_LENGTH in sync with whatever that app generates.
export const PASSCODE_LENGTH = 4;

// Every submitted passcode (right or wrong) counts. A 4-digit code is only 10,000 guesses,
// so after this many attempts the order is locked and a coordinator has to step in.
export const MAX_PASSCODE_ATTEMPTS = 5;
